kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pilatus-k8s
nodes:
- role: control-plane
  image: kindest/node:v1.28.6@sha256:e9e59d321795595d0eed0de48ef9fbda50388dc8bd4a9b23fb9bd869f370ec7e
  extraPortMappings:
    # containerPort below must match the values file:
    #   nginx-ingress.controller.service.nodePorts.http
    # Change hostPort if port 80 is already in use.
  - containerPort: 32080
    hostPort: 34080
    listenAddress: "0.0.0.0"
    # containerPort below must match the values file:
    #   nginx-ingress.controller.service.nodePorts.ssh
    # Using high-numbered hostPort assuming port 22 is
    #   already in use.
  - containerPort: 32022
    hostPort: 34022
    listenAddress: "0.0.0.0"
