apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp10-deployment
  namespace: default
  labels:
    app: warp10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warp10
  template:
    metadata:
      labels:
        app: warp10
    spec:
      securityContext:
        runAsUser: 499
        runAsGroup: 497
      containers:
        - name: warp10-container
          image: warp10-standaloneplus:1.0.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              ./bin/warp10.sh start && \
              ./bin/warp10.sh tokengen tokens/demo-tokengen.mc2 > /output/token_output.txt && \
              tail -f ./logs/warp10.log
          volumeMounts:
            - name: config-volume
              mountPath: /warp10/warpInstall/etc/fdb.cluster
              subPath: fdb.cluster
              readOnly: false
            - name: output-volume
              mountPath: /output
      volumes:
        - name: config-volume
          configMap:
            name: test-cluster-config
            items:
              - key: cluster-file
                path: fdb.cluster
        - name: output-volume
          emptyDir: {}