# helm install spark-hs . \
# --create-namespace --namespace spark 
# --set s3endpoint=${S3_ENDPOINT} \
# --set s3accessKey=${S3_ACCESS_KEY} \
# --set s3secretKey=${S3_SECRET_KEY} \
# --set s3logDirectory=s3a://spark/spark-logs \
# --set service.type=LoadBalancer \
# --set image.repository=gcr.io/myproject/spark
serviceAccount:
  create: true
  name: spark-hs


s3enabled: true
s3endpoint: 'http://minio:9000'
s3accessKey: 'minioadmin'
s3secretKey: 'minioadmin'
s3logDirectory: 's3a://spark/logs'
s3disableCertChecking: true